title: "Decidim dokumentation"
theme: "just-the-docs"
logo: /uploads/decidim-logo.svg
#color_scheme: "dark"
search_enabled: true
heading_anchors: true
footer_content: 'CC-BY 4.0 <a href="https://digidemlab.org">Digidem Lab</a>'
base_url: "decidim-docs"
plugins:
  - jekyll-redirect-from
